version: '3.5'

services:
    db_auth:
        container_name: poleeducation_db
        ports:
            - 5435:5432
        environment:
            - POSTGRES_PASSWORD=igor18052008
            - POSTGRES_USER=admin
        image: postgres
