version: '3.8'

services:
    backend:
        build:
            context: ./server
        ports:
            - '3002:3002' # Этот порт пробрасывается только внутри Docker сети
        env_file:
            - .env
        environment:
            - DATABASE_URL=postgres://fedigo_admin:Igor18052008@db_auth:5432/poleeducation
        depends_on:
            - db_auth

    frontend:
        build:
            context: ./client
        # Порты для фронтенда не пробрасываются наружу, он доступен только для Nginx
        depends_on:
            - backend

    nginx:
        image: nginx:alpine
        ports:
            - '80:80' # Nginx обслуживает наружные запросы на порт 80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf # Прокидывание конфигурационного файла
        depends_on:
            - frontend
            - backend

    db_auth:
        container_name: poleeducation_db
        image: postgres:16-alpine
        ports:
            - '5435:5432' # Пробрасывание порта для доступа к базе данных снаружи (если нужно)
        environment:
            - POSTGRES_DB=poleeducation_db
            - POSTGRES_USER=fedigo_admin
            - POSTGRES_PASSWORD=Igor18052008
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
