services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        container_name: backend
        ports:
            - '3002:3002'
        env_file:
            - .env.production
        environment:
            - NODE_ENV=production
        depends_on:
            - db_auth
        volumes:
            - upload_files_data:/backend/upload_files

    frontend-builder:
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
            target: builder # Используем только этап сборки
        environment:
            - VITE_API_URL=http://backend:3002
        container_name: frontend
        command: sh -c "npm run build" # Команда для сборки
        volumes:
            - build:/frontend/build

    db_auth:
        container_name: poleeducation_db
        image: postgres:16-alpine
        ports:
            - '5435:5432'
        environment:
            - POSTGRES_DB=poleeducation_db
            - POSTGRES_USER=fedigo_admin
            - POSTGRES_PASSWORD=Igor18052008
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./db_backups:/backups

volumes:
    db_data:
    build:
    upload_files_data:
